Add footer template
yesiddn/dreamy-event-front pull request #31
Opened 2024-05-07 20:57 UTC by CamiloBenavides

the footer was created

2024-05-07 21:01 UTC, AlejoShox approved these changes
Nice

2024-05-07 22:08 UTC, yesiddn requested changes
Cambiar nombre de iconos: bxl, 2.

2024-05-08 15:53 UTC, juanl-30 approved these changes

2024-05-08 15:57 UTC, yesiddn approved these changes

2024-05-08 15:58 UTC, merged